/* Generated by Amaranth Yosys 0.10.0 (PyPI ver 0.10.0.dev46, git sha1 dca8fb54a) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \initial  = 0;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:35" *)
  wire \$1 ;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:41" *)
  wire [16:0] \$3 ;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:41" *)
  wire [16:0] \$4 ;
  (* src = "/home/morris/.cache/pypoetry/virtualenvs/hello-amaranth-M2jrrid_-py3.10/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:30" *)
  reg [15:0] count = 16'h0000;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:30" *)
  reg [15:0] \count$next ;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:26" *)
  input en;
  (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:27" *)
  output ovf;
  (* src = "/home/morris/.cache/pypoetry/virtualenvs/hello-amaranth-M2jrrid_-py3.10/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  assign \$1  = count == (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:35" *) 5'h19;
  assign \$4  = count + (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:41" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\initial ) begin end
    \count$next  = count;
    (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:37" *)
    casez (en)
      /* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:37" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:38" *)
          casez (ovf)
            /* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:38" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "/home/morris/yosys_tangnano/blink/blink/counter.py:40" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "/home/morris/.cache/pypoetry/virtualenvs/hello-amaranth-M2jrrid_-py3.10/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
